[target.aarch64-unknown-none]
rustflags = [
    "--check-cfg=cfg(vm_debug)",
]

[env]
DEFMT_LOG = "debug"

[alias]
run-os = "run --package xtask"

# Force panic behavior to abort globally for bare-metal targets
[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

