[target.aarch64-unknown-none]
rustflags = [
    "--check-cfg=cfg(vm_debug)",
    # "--cfg", "vm_debug",
    "-C", "link-arg=-Tcrates/kernel/linker.ld"
]

# run
runner = "qemu-system-aarch64 -machine virt,gic-version=2 -cpu cortex-a53 -m 256M -nographic -serial mon:stdio -kernel"
# debug
# runner = "qemu-system-aarch64 -machine virt,gic-version=2 -cpu cortex-a53 -m 256M -nographic -serial mon:stdio -S -s -kernel"

[build]
target = "aarch64-unknown-none"

[env]
DEFMT_LOG = "debug"

[alias]
qemu = "run -p kernel --target aarch64-unknown-none"
qemu-release = "run -p kernel --release --target aarch64-unknown-none"

